# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile - VM Escape Game Cyber
# PFE L3B Groupe 3 — Drys Ferhi

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
  config.vm.hostname = "escape-game-cyber"

  # Réseau — accès aux défis depuis la machine hôte
  config.vm.network "forwarded_port", guest: 5000, host: 5000   # Flask web
  config.vm.network "forwarded_port", guest: 1337, host: 1337   # Défi réseau

  # Ressources VM
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "EscapeGameCyber"
    vb.memory = "1024"
    vb.cpus   = 1
  end

  # Provisionnement automatique
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y python3 python3-pip python3-venv git openssl steghide

    # Installation des dépendances Python
    cd /home/vagrant
    pip3 install flask --quiet

    echo "[+] VM Escape Game Cyber prête !"
    echo "[*] Lancez : python3 /vagrant/scripts/app.py"
  SHELL
end
